name: Upload to Azure Storage website

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob delete-batch --account-name vjkstaticsites -d '$web' --source ./_site/
            az storage blob upload-batch --account-name vjkstaticsites --source ./_site/            

  # Azure logout 
    - name: logout
      run: |
            az logout
      if: always()
